#!python

import os
import platform
import subprocess

AddOption('--prefix',
          dest='prefix',
          type='string',
          nargs=1,
          action='store',
          metavar='DIR',
          help='installation prefix')
env = Environment(PREFIX = GetOption('prefix'))
prefix  = os.environ.get('PREFIX')
base1 = os.path.abspath(os.path.join(prefix,os.pardir))
base = os.path.join(base1,'work')
sourcePath = os.path.join(base,'source')
binPath = os.path.join(prefix,'bin')

# Comment lines start with the # symbol
# The following sets up an Compile Environment Object with gfortran as the linker.
env = Environment(LINK='gfortran')
# The next line of code is an array of the source files names used in the program.
# The next line is the actual code that links the executable. env.Program is generates an executable.
grid_cloud_day = env.Program(target='grid_cloud_day', source= ['grid_cloud_day.f90'])
grid_cloud_night = env.Program(target='grid_cloud_night', source= ['grid_cloud_night.f90'])
agg_cloud = env.Program(target='agg_cloud', source= ['agg_cloud.f90'])

env.Install(binPath, [grid_cloud_day,grid_cloud_night,agg_cloud])
env.Alias('install', binPath)

